In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
arr=np.array(lst)
print(type(arr)) #ndim-->n dimentional


<class 'numpy.ndarray'>


In [4]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim) #1D array 1 rown 
print(b.ndim) #2D array 2 rows

1
2


In [5]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b.shape) #3 rows 4 columns
print(b.size) #12 elements
print(b.dtype) #int64

(3, 4)
12
int32


In [6]:
b=np.zeros((3,4)) #3 rows 4 columns  similaraly np.ones((3,4)) will give 1s
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Generate a 3x4 array with random values
random_array = np.random.random((3, 4)) # we can also not give the shape and it will generate a random value
print(random_array)


[[0.96613054 0.14234438 0.6206917  0.64399082]
 [0.1424725  0.24439304 0.26194907 0.32881081]
 [0.35452293 0.15317173 0.61299169 0.8387945 ]]


In [ ]:
np.arange(1,8,2).reshape(2,2) #start,stop,step
# Generate a 1D array with values from 0 to 9
#reshape is used to change the shape of the array

array([[1, 3],
       [5, 7]])

In [16]:
np.linspace(0, 1, 5) #start,stop,number of elements between start and stop
# Generate an array with 5 evenly spaced values between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])